region: us-east-1

function_name: agdq_backup
handler: service.handler
# role: lambda_basic_execution
description: Backs up current timeseries data to JSON in S3

# if access key and secret are left blank, boto will use the credentials
# defined in the [default] section of ~/.aws/credentials.
aws_access_key_id:
aws_secret_access_key:

# dist_directory: dist
timeout: 30
# memory_size: 512
